### ISSUE TITLE
Support Filament V3

### ISSUE THREAD

**Issue by Saifallak** [cms-multi/filament-clear-cache#12]

**Comment by faizananwerali** [comment]
+1

**Comment by howdu** [comment]
Added Filament v3 support to beta branch `cms-multi/filament-clear-cache": "2.0.0-beta1"`

**Comment by Saifallak** [comment]
thanks @howdu, i think today it should be out of beta! ♥ , thanks for your hard work.

**Comment by howdu** [comment]
Thanks! Please give it try version 2 is already released and out of beta :)
