### ISSUE TITLE
after install i cant see the clear button

### ISSUE THREAD

**Issue by agaitan026** [cms-multi/filament-clear-cache#29]
i followed docs but cant see clear cache button

```
use CmsMulti\FilamentClearCache\FilamentClearCachePlugin;

            ->plugin(
                \TomatoPHP\FilamentLogger\FilamentLoggerPlugin::make()
                ,FilamentClearCachePlugin::make())
```
what im missing?

**Comment by howdu** [comment]
That's correct. Have you made any changes to the config?

If the hook is working correctly it will be rendering the livewire component. 

Try to debug this file by removing the visible checks and see if that's the issue. 
<img width="855" alt="Screenshot 2024-09-26 at 15 36 39" src="https://github.com/user-attachments/assets/fddea0b5-56ed-491a-a778-fed676e1364d">

**Comment by davideprevosto** [comment]
@agaitan026 

I suppose you should fix from:

```php
->plugin(
                \TomatoPHP\FilamentLogger\FilamentLoggerPlugin::make()
                ,FilamentClearCachePlugin::make())
```

to

```php
->plugins([
                \TomatoPHP\FilamentLogger\FilamentLoggerPlugin::make(),
                FilamentClearCachePlugin::make()
                ])
```
