### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by githubenrico** [cms-multi/filament-clear-cache#5]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cms-multi/filament-clear-cache[dev-main, 1.0.0, ..., 1.0.5] require spatie/laravel-package-tools ^1.13.0 -> found spatie/laravel-package-tools[1.13.0, ..., 1.14.1] but the package is fixed to 1.12.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires cms-multi/filament-clear-cache * -> satisfiable by cms-multi/filament-clear-cache[dev-main, 1.0.0, ..., 1.0.5, 9999999-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require cms-multi/filament-clear-cache:*" to figure out if any version is installable, or "composer require cms-multi/filament-clear-cache:^2.1" if you know which you need.

**Comment by howdu** [comment]
Are you explicitly requiring version 1.12.1 of `spatie/laravel-package-tools` somewhere? 

Try again after deleting your composer.lock file. But I'm not able to reproduce this with the latest Filament. 

Also to be sure please check if it works with a clean install of Filament.
